nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - linux
    - darwin

packageExtensions:
  "@medusajs/medusa@*":
    dependencies:
      "@mikro-orm/core": "5.9.7"
      "@mikro-orm/knex": "5.9.7"
      "@mikro-orm/migrations": "5.9.7"
      "@mikro-orm/postgresql": "5.9.7"