version: "3.8"
services:
  postgres:
    image: postgres:16
    container_name: medusa-starter-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - medusa_database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis
    container_name: medusa-starter-redis
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "6379:6379"
    volumes:
      - medusa_redis:/data

volumes:
  medusa_database:
  medusa_redis: 